### ISSUE TITLE
Calculations for length and diameter of dousing tubes

### ISSUE THREAD

**Issue by sidneylok** [AguaClara/1-LPS#1]
Figure out how to increase major losses by completing calculations for length and diameter of the tubes based on flow stock

**Comment by ericamarroquin** [comment]
Things that I am going to need:
- Flow Rate! Are we going to be operating at full flow (1LPS) or at a lower flow rate?

**Comment by nataliemottl** [comment]
Did you decide on a flow rate and complete this step? We are trying to check in and make sure that teams are forging ahead! (Also encouraging teams to keep their issues and task lists up to date and complete!

**Comment by ericamarroquin** [comment]
Yup, working on it now! Flow rate is set, I'm just working to solidify the equations/code I'm using.

**Comment by ericamarroquin** [comment]
Calculations are done and were pushed to this repository. Checked over and confirmed by Monroe.
