### ISSUE TITLE
Building a lab bench

### ISSUE THREAD

**Issue by sidneylok** [AguaClara/1-LPS#10]
The DeFrees lab currently doesn't have a lab bench set up for our team. We are working with Paul to get this set up so we can run tests with turbidimeters and pumps on the plant later on in the semester.

**Comment by sidneylok** [comment]
We are currently waiting for our order for more 80/20 pieces to come in so we're at a standstill right now on this issue. But! We did get an actual table top on the bench skeleton we already had in the lab.

**Comment by ericamarroquin** [comment]
The 80/20 arrived and we began putting together the upper parts of the bench - the shelves that will hold our computer, turbidimeters, and pumps.

**Comment by sidneylok** [comment]
We are done! Pieces have been put on with Paul's help. We measured the 80/20 already on the lab benches in B60 and modeled it after those existing benches.
