### ISSUE TITLE
Run water through the plant without EStaRs

### ISSUE THREAD

**Issue by sidneylok** [AguaClara/1-LPS#4]
Run with through with water but without ESTaRs

**Comment by SungMinKim2795** [comment]
Set up the post and secured it 2.27. Will adjust the height of the CDC and lever arm after running water through the plant.

**Comment by ericamarroquin** [comment]
Plant is set up to water test. Flocculator was attached as well as the pipe to the drain from the exit launder. Ready to test tomorrow with our who team and Monroe!

**Comment by sidneylok** [comment]
Delayed because of drain issues. See Issue #15

**Comment by sidneylok** [comment]
3/27 The pole was slanted because there aren't washers on the bolts and the wood is pine so it's soft and moves. Erica ordered washers for it.

**Comment by SungMinKim2795** [comment]
Water has been successfully run through the plant numerous times!
