### ISSUE TITLE
Drain check before operation

### ISSUE THREAD

**Issue by monroews** [AguaClara/1-LPS#9]
Please check with Paul to ensure before running the plant to make sure that the plumbing is okay and that the drain is able to handle the flow.

Also determine whether the sludge can go down the drain or if it must be disposed of in a better way.

**Comment by sidneylok** [comment]
We checked with Paul yesterday and he said that the drain is alright, but to just be careful of the electrical box. I believe he only mentioned that we should not dump chemicals other than the PACl we're using in the plant down the drain. @sk2795 @emarroquin Clay was OK, right?

**Comment by SungMinKim2795** [comment]
Yes! We have to secure the tube so that it doesn't move around and be away from the electrical box but Paul checked that everything should be alright.
